server:
  port: 8018
spring:
  application:
    name: product-client
ribbon:
  eureka:
    enable: true
eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: true
    #下面一定要写 true
    fetch-registry: true
    initial-instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8888/eureka
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000  #连接超时时间2秒
        readTimeout: 5000     #读超时时间2秒
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000 #设置熔断时间1秒
